#import "./_PaginatorFragment.gql"

fragment CashFlowEntryParts on CashFlowEntry {
  id
  description
  date
  value
  is_expense
  receipt_path
  note
  confirmed_at
  created_at
  employee_name
}

fragment CashFlowEntryViaParts on CashFlowEntry {
  via {
    id
    name
  }
}

fragment CashFlowEntryTypeParts on CashFlowEntry {
  type {
    id
    name
  }
}

fragment CashFlowEntryOrderParts on CashFlowEntry {
  order {
    id
    code
    name
    quantity
    art_paths
    client {
      id
      name
    }
  }
}

fragment CashFlowEntryUserParts on CashFlowEntry {
  user {
    id
    name
  }
}

query GetCashFlowEntries (
  $first: Int = 10
  $page: Int
  $where: QueryCashFlowEntriesWhereWhereConditions
) {
  cashFlowEntries (
    first: $first
    page: $page
    where: $where
    orderBy: [
      {column: CREATED_AT order: DESC}
      {column: DATE order: DESC}
    ]
  ) {
    paginatorInfo {
      ...PaginatorSimpleParts
    }

    data {
      ...CashFlowEntryParts
      ...CashFlowEntryViaParts
      ...CashFlowEntryTypeParts
      ...CashFlowEntryOrderParts
      ...CashFlowEntryUserParts
    }
  }
}

query GetCashFlowStatistics ($input: CashFlowFilterDatesInput!) {
  cashFlowStatistics(input: $input) {
    created_orders
    created_shirts
    closed_orders
    closed_shirts
    no_payments_orders
    no_payments_shirts
    balance
  }
}
