query clothingTypes ($is_hidden: Boolean) {
  clothingTypes (is_hidden: $is_hidden) {
    id
    key
    name
    is_hidden
    commission
  }
}

mutation clothingTypeCreate ($input: ClothingTypeInput!) {
  clothingTypeCreate (input: $input) {
    id
  }
}

mutation clothingTypeUpdate ($id: ID! $input: ClothingTypeInput!) {
  clothingTypeUpdate (id: $id input: $input) {
    id
  }
}