query GetSalesAmount {
  dashboardSalesAmount {
    current {
      day
      week
      month
    }

    previous {
      day
      week
      month
    }
  }
}

query GetCitiesSalesAmount($month: SalesAmountCityMonth) {
  dashboardSalesAmountCities(month: $month) {
    city {
      id
      name
      state {
        id
        abbreviation
      }
    }

    amount
    shirts_count
    orders_count
  }
}
