#import "./_PaginatorFragment.gql"
query GetSalesAmount {
  dashboardSalesAmount {
    current {
      day
      week
      month
    }

    previous {
      day
      week
      month
    }
  }
}

query GetAmountSalesChart {
  dashboardSalesAmountChart {
    current {
      day
      amount
    }

    previous {
      day
      amount
    }
  }
}

query GetCitiesSalesAmount($date: String) {
  dashboardSalesAmountCities(date: $date) {
    city {
      id
      name
      state {
        id
        abbreviation
      }
    }

    amount
    shirts_count
    orders_count
  }
}

query GetModelsSalesAmount($date: SalesAmountModelDates!) {
  dashboardSalesAmountModels(date: $date) {
    model {
      id
      name
    }

    amount
    shirts_count
    sales_percentage
  }
}

query GetClientsSegmentation($date: ClientSegmentationDates!) {
  dashboardClientsSegmentation(date: $date) {
    new_clients {
      amount
      amount_pre_registered
      shirts_count
      orders_count
      orders_count_pre_registered
    }

    recurrent_clients {
      amount
      amount_pre_registered
      shirts_count
      orders_count
      orders_count_pre_registered
    }
  }
}

query GetDashboardMonthSalesUsers {
  dashboardMonthSalesUsers {
    user {
      id
      name
    }
    total
    percentage
  }
}

fragment DashboardProductionDataParts on DashboardProductionData {
  orders_count
  shirts_count
  receipt
}

fragment DashboardProductionOfDayParts on DashboardProductionOfDay {
  day {
    ...DashboardProductionDataParts
  }

  week {
    ...DashboardProductionDataParts
  }

  last_week {
    ...DashboardProductionDataParts
  }
}

query GetDashboardProduction($production_date: String!) {
  dashboardProduction(production_date: $production_date) {
    estampados {
      ...DashboardProductionOfDayParts
    }

    costurados {
      ...DashboardProductionOfDayParts
    }

    month_production {
      ...DashboardProductionDataParts
    }

    late_orders {
      ...DashboardProductionDataParts
    }

    waiting_for_withdrawal_orders {
      ...DashboardProductionDataParts
    }
  }
}

mutation ChangeDashboardProductionSettings(
  $settings: DashboardProductionSettings!
) {
  dashboardProductionSettings(settings: $settings)
}

query GetDashboardProductionOrders(
  $type: DashboardProductionOrdersTypes!
  $production_date: String
  $first: Int!
  $page: Int
) {
  dashboardProductionOrders(
    type: $type
    production_date: $production_date
    first: $first
    page: $page
  ) {
    paginatorInfo {
      ...PaginatorSimpleParts
    }

    data {
      id
      code
      price
      quantity
      delivery_date
      created_at
      linked_status {
        id
        text
        pivot {
          is_confirmed
          confirmed_at
        }
      }

      client {
        id
      }
    }
  }
}
