query GetSalesAmount {
  dashboardSalesAmount {
    current {
      day
      week
      month
    }

    previous {
      day
      week
      month
    }
  }
}

query GetCitiesSalesAmount($month: SalesAmountCityMonth) {
  dashboardSalesAmountCities(month: $month) {
    city {
      id
      name
      state {
        id
        abbreviation
      }
    }

    amount
    shirts_count
    orders_count
  }
}

query GetModelsSalesAmount($date: SalesAmountModelDates!) {
  dashboardSalesAmountModels(date: $date) {
    model {
      id
      name
    }

    amount
    shirts_count
    sales_percentage
  }
}

query GetClientsSegmentation($date: ClientSegmentationDates!) {
  dashboardClientsSegmentation(date: $date) {
    new_clients {
      amount
      amount_pre_registered
      shirts_count
      orders_count
      orders_count_pre_registered
    }

    recurrent_clients {
      amount
      amount_pre_registered
      shirts_count
      orders_count
      orders_count_pre_registered
    }
  }
}

fragment DashboardProductionStatusData on DashboardProductionStatus {
  orders_count {
    day
    week
    last_week
  }

  receipt {
    day
    week
    last_week
  }
}

query GetMonthProduction {
  dashboardProduction {
    estampados {
      ...DashboardProductionStatusData
    }

    costurados {
      ...DashboardProductionStatusData
    }

    month_production {
      orders_count
      receipt
    }

    late_orders
    waiting_for_withdrawal_orders
  }
}
