query GetEntries(
  $first: Int!
  $page: Int
  $where: QueryEntriesWhereWhereConditions
) {
  entries(first: $first, page: $page, where: $where) {
    data {
      id
      bank_uid
      value
      date
      description
      is_canceled
      via_id
    }
  }
}

query GetEntriesMonthlyBalance {
  entriesMonthlyBalance
}

mutation CancelEntry($uid: ID!) {
  entryCancel(uid: $uid) {
    id
  }
}
