#import "./_PaginatorFragment.gql"

fragment CommissionParts on Commission {
  id
  print_commission
  seam_commission
  seam_total_commission
  print_total_commission
}

fragment CommissionUserParts on CommissionUser {
  id
  commission_value
  confirmed_at
  was_quantity_changed
  role {
    id
    name
  }
}

fragment CommissionOrderParts on Order {
  id
  code
  quantity
  art_paths
  size_paths
  created_at
  updated_at
  client {
    id
  }
}

query GetAuthUserCommissions ($page: Int) {
  commissionsUser (page: $page first: 10) {
    paginatorInfo {
      ...PaginatorSimpleParts
    }

    data {
      ...CommissionParts
      pivot {
        ...CommissionUserParts
      }
      order {
        ...CommissionOrderParts
      }
    }
  }
}

query GetUsersCommissions (
  $page: Int
  $where: QueryCommissionsUsersWhereWhereConditions
  $orderBy: [QueryCommissionsUsersOrderByOrderByClause!]
) {
  commissionsUsers (first: 10 page: $page where: $where orderBy: $orderBy) {
    paginatorInfo {
      ...PaginatorSimpleParts
    }

    data {
      id
      user {
        id
        name
      }

      commission {
        ...CommissionParts
        order {
          ...CommissionOrderParts
        }
      }
      ...CommissionUserParts
    }
  }
}

query GetMonthCommissionByRole ($role_id: ID $month: String!) {
  commissionRoleByMonth (role_id: $role_id month: $month) {
    month
    year
    value
    role {
      id
      name
    }
  }
}

mutation UpsertCommissionValue($value: String!) {
  commissionValueUpsert(value: $value)
}

mutation ConfirmCommissionProduction ($id: ID!) {
  commissionConfirmProduction (id: $id) {
      ...CommissionParts
      pivot {
        ...CommissionUserParts
      }
      order {
        ...CommissionOrderParts
      }
  }
}
