#import "./_PaginatorFragment.gql"

query GetReceiptProductSuggestions {
  receiptProductSuggestions
}

query GetReceipts($first: Int!, $page: Int) {
  receipts(first: $first, page: $page) {
    paginatorInfo {
      ...PaginatorSimpleParts
    }

    data {
      id
      client
      product
      value
      filepath
      date
      has_signature
    }
  }
}

mutation GetReceiptURL($id: ID, $preview: Boolean) {
  receiptUrl(id: $id, preview: $preview)
}

mutation CreateReceipt($input: ReceiptInput!) {
  receiptCreate(input: $input) {
    id
  }
}

mutation UpdateReceipt($id: ID!, $input: ReceiptInput!) {
  receiptUpdate(id: $id, input: $input) {
    id
  }
}

mutation UploadReceiptGeneratorSettings($input: ReceiptSettingsInput!) {
  receiptGeneratorSettingsUpload(input: $input) {
    id
    name
    json
  }
}
