fragment User on User {
  id
  name
  email
  created_at
  role {
    id
    name
  }
}

query GetUsers {
  users {
    ...User
  }
}

mutation userCreate($input: UserInput!) {
  userCreate(input: $input) {
    ...User
  }
}

mutation EditUser ($id: ID! $input: UserEditInput!) {
  userEdit(id: $id input: $input) {
    ...User
  }
}

mutation userDelete($id: ID! $auth_password: String!) {
  userDelete(id: $id auth_password: $auth_password) {
    ...User
  }
}
